### ISSUE TITLE
bug of header in markdown

### ISSUE THREAD

**Issue by redVi** [promek/wombat-light-syntax#2]
The line immediately after the heading looks very... strange. Bug appears only with this theme.
The reason for this behavior in the established sizes of the header.

``` less
.markup.heading.heading-1 {
  font-size : ~"calc(30px)";
}
```

![markdown-header-bug](https://cloud.githubusercontent.com/assets/2623486/11689519/3a554faa-9eb4-11e5-907b-3d7a5825f282.png)
